-- DROP DATABASE IF EXISTS content;
--
-- CREATE DATABASE content;
--
-- USE  content;
--
-- CREATE TABLE box(
--   id int NOT NULL AUTO_INCREMENT,
--   comments varchar(250) NOT NULL,
--   user varchar(60) NOT NULL,
--   PRIMARY KEY (ID)
-- );

-- INSERT INTO box (user, comment) VALUES ();
